# Generated by Django 5.0.7 on 2024-07-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('number_count', models.IntegerField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Files/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Files/images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Files/images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='Files/images/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='Files/pdfs/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='Files/videos/')),
                ('dp_image', models.ImageField(blank=True, null=True, upload_to='Files/dp_images/')),
                ('reply_button1', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_button2', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_action1', models.URLField(blank=True, null=True)),
                ('call_to_action2', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
