# Generated by Django 5.0.7 on 2024-07-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesendapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendwhatsapp',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sendwhatsapp',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sendwhatsapp',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sendwhatsapp',
            name='number_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
