# Generated by Django 5.0.7 on 2024-07-09 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesendapp', '0003_reseller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CampaignWise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_time', models.DurationField(blank=True, null=True)),
                ('update_status', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('rollback', models.BooleanField(blank=True, default=False, null=True)),
                ('total_mobile_no', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_user_type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
