# Generated by Django 5.0.7 on 2024-07-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesendapp', '0004_alter_reseller_status_campaignwise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignwise',
            name='rollback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
