# Generated by Django 5.0.7 on 2024-07-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wesendapp', '0009_alter_campaignwise_created_user_type_creditreport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditReport',
            new_name='Report',
        ),
    ]
