# Generated by Django 5.0.7 on 2024-07-11 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wesendapp', '0012_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
    ]
