# Generated by Django 5.0.7 on 2024-07-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesendapp', '0013_remove_user_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_id',
            new_name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
