# Generated by Django 5.0.7 on 2024-07-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesendapp', '0016_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='credit',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
